import type { ScrapedDeal } from './types'

export const SEED_DEALS: ScrapedDeal[] = [
  // ── SaaS / Tech ──────────────────────────────────────────────
  {
    source: 'seed',
    brand_name: 'Shopify',
    logo_url: 'https://logo.clearbit.com/shopify.com',
    title: 'Shopify Affiliate Program — 20% recurring commission',
    description: 'Earn 20% of monthly subscription fees for up to 12 months for every merchant you refer. One of the highest-paying e-commerce affiliate programs.',
    type: 'affiliate',
    niches: ['E-commerce', 'Business', 'Tech'],
    platforms: ['youtube', 'instagram', 'blog'],
    commission_rate: 20,
    budget_min: null,
    budget_max: null,
    min_followers: 1000,
    apply_url: 'https://www.shopify.com/affiliates',
    is_featured: true,
  },
  {
    source: 'seed',
    brand_name: 'HubSpot',
    logo_url: 'https://logo.clearbit.com/hubspot.com',
    title: 'HubSpot Affiliate Program — 30% recurring for 1 year',
    description: 'Earn 30% recurring commission for up to 12 months on all HubSpot product sales. Average payout is $276/month per active referral.',
    type: 'affiliate',
    niches: ['B2B', 'Marketing', 'Business'],
    platforms: ['youtube', 'blog', 'linkedin'],
    commission_rate: 30,
    budget_min: null,
    budget_max: null,
    min_followers: 5000,
    apply_url: 'https://www.hubspot.com/partners/affiliates',
    is_featured: true,
  },
  {
    source: 'seed',
    brand_name: 'Semrush',
    logo_url: 'https://logo.clearbit.com/semrush.com',
    title: 'Semrush Affiliate Program — Up to 40% commission',
    description: 'Earn $200 per sale, $10 per trial, $0.01 per sign-up. One of the most generous SaaS affiliate programs for marketing creators.',
    type: 'affiliate',
    niches: ['Marketing', 'SEO', 'B2B'],
    platforms: ['youtube', 'blog'],
    commission_rate: 40,
    budget_min: null,
    budget_max: null,
    min_followers: 1000,
    apply_url: 'https://www.semrush.com/partner/affiliate/',
    is_featured: true,
  },
  {
    source: 'seed',
    brand_name: 'NordVPN',
    logo_url: 'https://logo.clearbit.com/nordvpn.com',
    title: 'NordVPN Creator Program — Up to 100% CPA + 30% recurring',
    description: 'Earn up to 100% commission on the first payment and 30% on renewals. Dedicated affiliate manager and custom promo codes.',
    type: 'affiliate',
    niches: ['Tech', 'Gaming', 'Privacy'],
    platforms: ['youtube', 'tiktok', 'instagram'],
    commission_rate: 40,
    budget_min: null,
    budget_max: null,
    min_followers: 5000,
    apply_url: 'https://affiliates.nordvpn.com',
    is_featured: true,
  },
  {
    source: 'seed',
    brand_name: 'Canva',
    logo_url: 'https://logo.clearbit.com/canva.com',
    title: 'Canva Affiliate Program — 80% first month, 20% recurring',
    description: 'Earn 80% commission on the first payment and 20% on all future renewals. Massive audience with 100M+ users.',
    type: 'affiliate',
    niches: ['Design', 'Creative', 'Business'],
    platforms: ['youtube', 'instagram', 'blog'],
    commission_rate: 80,
    budget_min: null,
    budget_max: null,
    min_followers: 1000,
    apply_url: 'https://www.canva.com/affiliates/',
    is_featured: false,
  },
  {
    source: 'seed',
    brand_name: 'Fiverr',
    logo_url: 'https://logo.clearbit.com/fiverr.com',
    title: 'Fiverr Affiliates — Up to $150 CPA per referral',
    description: "Earn $15–$150 per first-time buyer depending on the service category. Plus 10% revenue share for 12 months with Fiverr Hybrid.",
    type: 'affiliate',
    niches: ['Freelance', 'Business', 'Tech'],
    platforms: ['youtube', 'blog', 'instagram'],
    commission_rate: null,
    budget_min: 15,
    budget_max: 150,
    min_followers: 1000,
    apply_url: 'https://affiliates.fiverr.com',
    is_featured: false,
  },
  {
    source: 'seed',
    brand_name: 'Coursera',
    logo_url: 'https://logo.clearbit.com/coursera.org',
    title: 'Coursera Affiliate Program — 45% on course sales',
    description: 'Earn 45% commission on courses, certificates, and degrees. Average order value is $90+.',
    type: 'affiliate',
    niches: ['Education', 'Courses', 'Career'],
    platforms: ['youtube', 'blog', 'instagram'],
    commission_rate: 45,
    budget_min: null,
    budget_max: null,
    min_followers: 1000,
    apply_url: 'https://about.coursera.org/affiliates',
    is_featured: false,
  },
  {
    source: 'seed',
    brand_name: 'Skillshare',
    logo_url: 'https://logo.clearbit.com/skillshare.com',
    title: 'Skillshare Affiliate — $7 per new Premium member trial',
    description: 'Earn $7 for every new Premium member who starts a trial. 30-day cookie window.',
    type: 'affiliate',
    niches: ['Education', 'Creative', 'Design'],
    platforms: ['youtube', 'instagram', 'tiktok'],
    commission_rate: null,
    budget_min: 7,
    budget_max: 7,
    min_followers: 1000,
    apply_url: 'https://www.skillshare.com/affiliates',
    is_featured: false,
  },
  {
    source: 'seed',
    brand_name: 'Grammarly',
    logo_url: 'https://logo.clearbit.com/grammarly.com',
    title: 'Grammarly Affiliates — $0.20/free signup + $20/premium',
    description: 'Earn $0.20 per qualified free account + $20 per Premium upgrade. Massive brand recognition, high conversion rates.',
    type: 'affiliate',
    niches: ['Education', 'Writing', 'Productivity'],
    platforms: ['youtube', 'blog', 'tiktok'],
    commission_rate: null,
    budget_min: null,
    budget_max: null,
    min_followers: 1000,
    apply_url: 'https://www.grammarly.com/affiliates',
    is_featured: false,
  },
  {
    source: 'seed',
    brand_name: 'Adobe',
    logo_url: 'https://logo.clearbit.com/adobe.com',
    title: 'Adobe Affiliate Program — 85% commission first month',
    description: "Earn 85% of the first month's subscription fee on all Creative Cloud plans, then 8.33% monthly recurring.",
    type: 'affiliate',
    niches: ['Design', 'Creative', 'Photography'],
    platforms: ['youtube', 'instagram', 'blog'],
    commission_rate: 85,
    budget_min: null,
    budget_max: null,
    min_followers: 1000,
    apply_url: 'https://www.adobe.com/affiliates.html',
    is_featured: false,
  },
  {
    source: 'seed',
    brand_name: 'Squarespace',
    logo_url: 'https://logo.clearbit.com/squarespace.com',
    title: 'Squarespace Affiliate Program — Up to $200 per sale',
    description: 'Earn a flat commission for every new customer you refer. Payouts range from $100–$200 depending on the plan.',
    type: 'affiliate',
    niches: ['Design', 'Business', 'E-commerce'],
    platforms: ['youtube', 'instagram', 'blog'],
    commission_rate: null,
    budget_min: 100,
    budget_max: 200,
    min_followers: 5000,
    apply_url: 'https://www.squarespace.com/affiliates',
    is_featured: false,
  },
  {
    source: 'seed',
    brand_name: 'Wix',
    logo_url: 'https://logo.clearbit.com/wix.com',
    title: 'Wix Partner Program — $100 per premium sale',
    description: 'Earn $100 for every new Wix Premium plan purchase. 30-day cookie duration.',
    type: 'affiliate',
    niches: ['Design', 'Business', 'E-commerce'],
    platforms: ['youtube', 'blog', 'instagram'],
    commission_rate: null,
    budget_min: 100,
    budget_max: 100,
    min_followers: 1000,
    apply_url: 'https://www.wix.com/upgrade/website/affiliates',
    is_featured: false,
  },
  {
    source: 'seed',
    brand_name: 'ConvertKit',
    logo_url: 'https://logo.clearbit.com/convertkit.com',
    title: 'Kit (ConvertKit) Affiliate — 30% recurring lifetime',
    description: 'Earn 30% monthly recurring commission for the lifetime of each customer you refer. 60-day cookie window.',
    type: 'affiliate',
    niches: ['Marketing', 'Business', 'Creators'],
    platforms: ['youtube', 'blog', 'twitter'],
    commission_rate: 30,
    budget_min: null,
    budget_max: null,
    min_followers: 1000,
    apply_url: 'https://convertkit.com/affiliate',
    is_featured: false,
  },
  {
    source: 'seed',
    brand_name: 'Teachable',
    logo_url: 'https://logo.clearbit.com/teachable.com',
    title: 'Teachable Affiliate Program — 30% recurring commission',
    description: 'Earn 30% monthly recurring commission for every creator who signs up via your link. Average creator earns $45/month per referral.',
    type: 'affiliate',
    niches: ['Education', 'Business', 'Creators'],
    platforms: ['youtube', 'blog', 'instagram'],
    commission_rate: 30,
    budget_min: null,
    budget_max: null,
    min_followers: 1000,
    apply_url: 'https://teachable.com/affiliates',
    is_featured: false,
  },
  {
    source: 'seed',
    brand_name: 'Kajabi',
    logo_url: 'https://logo.clearbit.com/kajabi.com',
    title: 'Kajabi Partner Program — 30% lifetime recurring',
    description: 'Earn 30% monthly recurring commission for the lifetime of each customer. High AOV platform targeted at serious creators.',
    type: 'affiliate',
    niches: ['Education', 'Creators', 'Business'],
    platforms: ['youtube', 'blog'],
    commission_rate: 30,
    budget_min: null,
    budget_max: null,
    min_followers: 5000,
    apply_url: 'https://kajabi.com/affiliate',
    is_featured: false,
  },
  {
    source: 'seed',
    brand_name: 'ClickFunnels',
    logo_url: 'https://logo.clearbit.com/clickfunnels.com',
    title: 'ClickFunnels Affiliate — 40% recurring commission',
    description: 'Earn 40% monthly recurring commission on all ClickFunnels subscriptions plus 40% on other products.',
    type: 'affiliate',
    niches: ['Marketing', 'Business', 'E-commerce'],
    platforms: ['youtube', 'blog'],
    commission_rate: 40,
    budget_min: null,
    budget_max: null,
    min_followers: 5000,
    apply_url: 'https://affiliates.clickfunnels.com',
    is_featured: false,
  },
  {
    source: 'seed',
    brand_name: 'Surfshark',
    logo_url: 'https://logo.clearbit.com/surfshark.com',
    title: 'Surfshark Affiliate Program — Up to 40% commission + bonuses',
    description: 'Earn up to 40% commission per sale plus performance bonuses. Custom coupon codes and real-time dashboard.',
    type: 'affiliate',
    niches: ['Tech', 'Privacy', 'Gaming'],
    platforms: ['youtube', 'tiktok', 'instagram'],
    commission_rate: 40,
    budget_min: null,
    budget_max: null,
    min_followers: 1000,
    apply_url: 'https://surfshark.com/affiliates',
    is_featured: false,
  },
  {
    source: 'seed',
    brand_name: 'Dashlane',
    logo_url: 'https://logo.clearbit.com/dashlane.com',
    title: 'Dashlane Affiliates — Premium password manager',
    description: 'Earn commission promoting the leading password manager. High conversion rates in the security/privacy niche.',
    type: 'affiliate',
    niches: ['Tech', 'Privacy', 'Security'],
    platforms: ['youtube', 'blog'],
    commission_rate: 25,
    budget_min: null,
    budget_max: null,
    min_followers: 1000,
    apply_url: 'https://www.dashlane.com/partners/affiliate',
    is_featured: false,
  },
  {
    source: 'seed',
    brand_name: 'Hootsuite',
    logo_url: 'https://logo.clearbit.com/hootsuite.com',
    title: 'Hootsuite Affiliate Program — 15% commission',
    description: 'Earn 15% commission on every new Hootsuite subscription. Dedicated affiliate team and custom creative assets.',
    type: 'affiliate',
    niches: ['Marketing', 'Social Media', 'B2B'],
    platforms: ['blog', 'youtube', 'linkedin'],
    commission_rate: 15,
    budget_min: null,
    budget_max: null,
    min_followers: 5000,
    apply_url: 'https://www.hootsuite.com/partners/affiliates',
    is_featured: false,
  },
  {
    source: 'seed',
    brand_name: 'Buffer',
    logo_url: 'https://logo.clearbit.com/buffer.com',
    title: 'Buffer Affiliate Program — 20% recurring commission',
    description: 'Earn 20% monthly recurring commission for every Buffer subscriber you refer. 45-day cookie window.',
    type: 'affiliate',
    niches: ['Marketing', 'Social Media', 'Business'],
    platforms: ['blog', 'youtube', 'twitter'],
    commission_rate: 20,
    budget_min: null,
    budget_max: null,
    min_followers: 1000,
    apply_url: 'https://buffer.com/affiliate-program',
    is_featured: false,
  },
  // ── E-commerce ───────────────────────────────────────────────
  {
    source: 'seed',
    brand_name: 'Amazon',
    logo_url: 'https://logo.clearbit.com/amazon.com',
    title: 'Amazon Associates — 1–10% on millions of products',
    description: 'Earn 1–10% commission on virtually any product on Amazon. Cookie credits for 24 hours after click.',
    type: 'affiliate',
    niches: ['Lifestyle', 'Tech', 'Home', 'Fashion'],
    platforms: ['youtube', 'instagram', 'blog', 'tiktok'],
    commission_rate: 5,
    budget_min: null,
    budget_max: null,
    min_followers: 500,
    apply_url: 'https://affiliate-program.amazon.com',
    is_featured: false,
  },
  {
    source: 'seed',
    brand_name: 'Etsy',
    logo_url: 'https://logo.clearbit.com/etsy.com',
    title: 'Etsy Affiliate Program — 4% commission',
    description: 'Earn 4% on Etsy purchases from your links. Millions of unique, handmade, and vintage items to promote.',
    type: 'affiliate',
    niches: ['Lifestyle', 'Fashion', 'Home', 'Art'],
    platforms: ['instagram', 'blog'],
    commission_rate: 4,
    budget_min: null,
    budget_max: null,
    min_followers: 1000,
    apply_url: 'https://www.etsy.com/affiliates',
    is_featured: false,
  },
  {
    source: 'seed',
    brand_name: 'Thrive Market',
    logo_url: 'https://logo.clearbit.com/thrivemarket.com',
    title: 'Thrive Market Affiliates — 25–30% on memberships',
    description: 'Earn 25–30% on every new paid membership. Organic food and wellness brand with strong creator affinity.',
    type: 'affiliate',
    niches: ['Health', 'Food', 'Wellness'],
    platforms: ['instagram', 'youtube', 'tiktok'],
    commission_rate: 30,
    budget_min: null,
    budget_max: null,
    min_followers: 5000,
    apply_url: 'https://thrivemarket.com/affiliate',
    is_featured: false,
  },
  // ── Fashion / Beauty ─────────────────────────────────────────
  {
    source: 'seed',
    brand_name: 'SHEIN',
    logo_url: 'https://logo.clearbit.com/shein.com',
    title: 'SHEIN Affiliate Program — 10–20% commission',
    description: 'Earn 10–20% on all orders. Custom discount codes for your audience. One of the highest-volume fashion affiliate programs.',
    type: 'affiliate',
    niches: ['Fashion', 'Lifestyle'],
    platforms: ['instagram', 'tiktok', 'youtube'],
    commission_rate: 15,
    budget_min: null,
    budget_max: null,
    min_followers: 1000,
    apply_url: 'https://affiliate.shein.com',
    is_featured: false,
  },
  {
    source: 'seed',
    brand_name: 'ASOS',
    logo_url: 'https://logo.clearbit.com/asos.com',
    title: 'ASOS Affiliate Program — 6% commission',
    description: 'Earn 6% on all ASOS products. Large catalogue, strong brand recognition, 30-day cookie window.',
    type: 'affiliate',
    niches: ['Fashion', 'Lifestyle'],
    platforms: ['instagram', 'tiktok', 'youtube'],
    commission_rate: 6,
    budget_min: null,
    budget_max: null,
    min_followers: 1000,
    apply_url: 'https://www.asos.com/discover/affiliate-programme/',
    is_featured: false,
  },
  {
    source: 'seed',
    brand_name: 'Nike',
    logo_url: 'https://logo.clearbit.com/nike.com',
    title: 'Nike Affiliate Program — 11% commission',
    description: "Earn 11% on Nike.com sales. Promote the world's leading athletic brand with millions of products.",
    type: 'affiliate',
    niches: ['Fitness', 'Fashion', 'Sports'],
    platforms: ['instagram', 'tiktok', 'youtube'],
    commission_rate: 11,
    budget_min: null,
    budget_max: null,
    min_followers: 5000,
    apply_url: 'https://www.nike.com/help/a/affiliate-programs',
    is_featured: false,
  },
  {
    source: 'seed',
    brand_name: 'Adidas',
    logo_url: 'https://logo.clearbit.com/adidas.com',
    title: 'Adidas Affiliate Program — 7% commission',
    description: 'Earn 7% on adidas.com sales. Dedicated creative assets, 30-day cookie window.',
    type: 'affiliate',
    niches: ['Fitness', 'Fashion', 'Sports'],
    platforms: ['instagram', 'tiktok', 'youtube'],
    commission_rate: 7,
    budget_min: null,
    budget_max: null,
    min_followers: 5000,
    apply_url: 'https://www.adidas.com/us/affiliate-program',
    is_featured: false,
  },
  {
    source: 'seed',
    brand_name: 'Sephora',
    logo_url: 'https://logo.clearbit.com/sephora.com',
    title: 'Sephora Collection Affiliate — 5–10% commission',
    description: 'Earn 5–10% on Sephora purchases. High AOV beauty brand with loyal creator community.',
    type: 'affiliate',
    niches: ['Beauty', 'Skincare', 'Lifestyle'],
    platforms: ['instagram', 'tiktok', 'youtube'],
    commission_rate: 8,
    budget_min: null,
    budget_max: null,
    min_followers: 5000,
    apply_url: 'https://www.sephora.com/beauty/affiliate-program',
    is_featured: true,
  },
  {
    source: 'seed',
    brand_name: 'Gymshark',
    logo_url: 'https://logo.clearbit.com/gymshark.com',
    title: 'Gymshark Affiliate Program — 5–10% commission',
    description: 'Earn 5–10% on all Gymshark orders. Creator-first brand with strong fitness community. Custom discount codes.',
    type: 'affiliate',
    niches: ['Fitness', 'Fashion', 'Health'],
    platforms: ['instagram', 'tiktok', 'youtube'],
    commission_rate: 8,
    budget_min: null,
    budget_max: null,
    min_followers: 10000,
    apply_url: 'https://www.gymshark.com/pages/affiliate',
    is_featured: false,
  },
  {
    source: 'seed',
    brand_name: 'Fashion Nova',
    logo_url: 'https://logo.clearbit.com/fashionnova.com',
    title: 'Fashion Nova Influencer Program — 20% commission',
    description: 'Earn 20% on all sales. One of the most creator-friendly fast fashion brands. Fast approval.',
    type: 'affiliate',
    niches: ['Fashion', 'Lifestyle'],
    platforms: ['instagram', 'tiktok'],
    commission_rate: 20,
    budget_min: null,
    budget_max: null,
    min_followers: 1000,
    apply_url: 'https://www.fashionnova.com/pages/influencer',
    is_featured: false,
  },
  // ── Health & Wellness ────────────────────────────────────────
  {
    source: 'seed',
    brand_name: 'AG1',
    logo_url: 'https://logo.clearbit.com/drinkag1.com',
    title: 'AG1 Creator Program — $18 per subscription sale',
    description: 'Earn $18 per first subscription order. High-converting health supplement with creator-friendly materials.',
    type: 'affiliate',
    niches: ['Health', 'Fitness', 'Wellness'],
    platforms: ['youtube', 'instagram', 'podcast'],
    commission_rate: null,
    budget_min: 18,
    budget_max: 18,
    min_followers: 10000,
    apply_url: 'https://drinkag1.com/affiliates',
    is_featured: true,
  },
  {
    source: 'seed',
    brand_name: 'Ritual',
    logo_url: 'https://logo.clearbit.com/ritual.com',
    title: 'Ritual Vitamins Affiliate — 20% commission',
    description: 'Earn 20% on all Ritual vitamin orders. High-quality DTC supplement brand with strong influencer affinity.',
    type: 'affiliate',
    niches: ['Health', 'Wellness', 'Fitness'],
    platforms: ['instagram', 'tiktok', 'youtube'],
    commission_rate: 20,
    budget_min: null,
    budget_max: null,
    min_followers: 5000,
    apply_url: 'https://ritual.com/affiliates',
    is_featured: false,
  },
  {
    source: 'seed',
    brand_name: 'Calm',
    logo_url: 'https://logo.clearbit.com/calm.com',
    title: 'Calm Affiliate Program — 25% commission',
    description: 'Earn 25% on all new Calm subscriptions. Leading meditation and sleep app with broad audience appeal.',
    type: 'affiliate',
    niches: ['Wellness', 'Mental Health', 'Lifestyle'],
    platforms: ['instagram', 'youtube', 'podcast'],
    commission_rate: 25,
    budget_min: null,
    budget_max: null,
    min_followers: 5000,
    apply_url: 'https://www.calm.com/affiliates',
    is_featured: false,
  },
  {
    source: 'seed',
    brand_name: 'Headspace',
    logo_url: 'https://logo.clearbit.com/headspace.com',
    title: 'Headspace Affiliate Program — Up to 35% commission',
    description: 'Earn 10–35% on new Headspace subscriptions. Trusted mindfulness app, strong brand recognition.',
    type: 'affiliate',
    niches: ['Wellness', 'Mental Health', 'Productivity'],
    platforms: ['instagram', 'youtube', 'podcast'],
    commission_rate: 25,
    budget_min: null,
    budget_max: null,
    min_followers: 5000,
    apply_url: 'https://www.headspace.com/affiliates',
    is_featured: false,
  },
  {
    source: 'seed',
    brand_name: 'Eight Sleep',
    logo_url: 'https://logo.clearbit.com/eightsleep.com',
    title: 'Eight Sleep Affiliate Program — 5% per mattress sale',
    description: 'Earn 5% on high-AOV smart mattress purchases ($2,000+). Popular in tech, fitness, and biohacking niches.',
    type: 'affiliate',
    niches: ['Health', 'Fitness', 'Tech', 'Biohacking'],
    platforms: ['youtube', 'instagram', 'podcast'],
    commission_rate: 5,
    budget_min: null,
    budget_max: null,
    min_followers: 10000,
    apply_url: 'https://www.eightsleep.com/affiliate',
    is_featured: false,
  },
  // ── Food & Drink ─────────────────────────────────────────────
  {
    source: 'seed',
    brand_name: 'HelloFresh',
    logo_url: 'https://logo.clearbit.com/hellofresh.com',
    title: 'HelloFresh Affiliate Program — $10–$25 per new subscriber',
    description: "Earn $10–$25 for every new customer who completes their first box. World's largest meal kit delivery service.",
    type: 'affiliate',
    niches: ['Food', 'Lifestyle', 'Health'],
    platforms: ['instagram', 'youtube', 'tiktok'],
    commission_rate: null,
    budget_min: 10,
    budget_max: 25,
    min_followers: 5000,
    apply_url: 'https://www.hellofresh.com/pages/affiliate',
    is_featured: false,
  },
  // ── Travel ───────────────────────────────────────────────────
  {
    source: 'seed',
    brand_name: 'Booking.com',
    logo_url: 'https://logo.clearbit.com/booking.com',
    title: 'Booking.com Affiliate Partner Program — 4% commission',
    description: "Earn 4% on completed hotel/property bookings. World's largest accommodation platform, massive global reach.",
    type: 'affiliate',
    niches: ['Travel', 'Lifestyle'],
    platforms: ['blog', 'youtube', 'instagram'],
    commission_rate: 4,
    budget_min: null,
    budget_max: null,
    min_followers: 1000,
    apply_url: 'https://www.booking.com/affiliate-program/',
    is_featured: false,
  },
  {
    source: 'seed',
    brand_name: 'Viator',
    logo_url: 'https://logo.clearbit.com/viator.com',
    title: 'Viator Affiliate Program — 8% on tours and experiences',
    description: 'Earn 8% on all booked tours, activities, and experiences. 300,000+ experiences in 2,500+ destinations.',
    type: 'affiliate',
    niches: ['Travel', 'Lifestyle'],
    platforms: ['blog', 'youtube', 'instagram'],
    commission_rate: 8,
    budget_min: null,
    budget_max: null,
    min_followers: 1000,
    apply_url: 'https://www.viator.com/partnerships',
    is_featured: false,
  },
  // ── Finance ──────────────────────────────────────────────────
  {
    source: 'seed',
    brand_name: 'Wise',
    logo_url: 'https://logo.clearbit.com/wise.com',
    title: 'Wise Affiliate Program — Earn per qualified transfer',
    description: 'Earn commission for every qualified user who sends money with Wise. Great for finance, expat, and travel creators.',
    type: 'affiliate',
    niches: ['Finance', 'Travel', 'Business'],
    platforms: ['youtube', 'blog'],
    commission_rate: null,
    budget_min: 10,
    budget_max: 50,
    min_followers: 5000,
    apply_url: 'https://wise.com/affiliates',
    is_featured: false,
  },
  {
    source: 'seed',
    brand_name: 'Coinbase',
    logo_url: 'https://logo.clearbit.com/coinbase.com',
    title: 'Coinbase Affiliate Program — $10 per referred user',
    description: 'Earn $10 per new Coinbase user who buys or sells $100+. Leading US crypto exchange.',
    type: 'affiliate',
    niches: ['Finance', 'Crypto', 'Tech'],
    platforms: ['youtube', 'blog', 'twitter'],
    commission_rate: null,
    budget_min: 10,
    budget_max: 10,
    min_followers: 5000,
    apply_url: 'https://www.coinbase.com/affiliates',
    is_featured: false,
  },
  // ── Brand Deals ──────────────────────────────────────────────
  {
    source: 'seed',
    brand_name: 'Sephora',
    logo_url: 'https://logo.clearbit.com/sephora.com',
    title: 'Sephora Squad 2025 — Open Brand Ambassador Applications',
    description: 'Apply to become a Sephora Squad member. Selected ambassadors receive products, payment, and dedicated brand support for year-long partnership.',
    type: 'brand_deal',
    niches: ['Beauty', 'Skincare', 'Lifestyle'],
    platforms: ['instagram', 'tiktok', 'youtube'],
    commission_rate: null,
    budget_min: 1000,
    budget_max: 10000,
    min_followers: 1000,
    apply_url: 'https://www.sephora.com/beauty/sephora-squad',
    is_featured: true,
  },
  {
    source: 'seed',
    brand_name: 'Away',
    logo_url: 'https://logo.clearbit.com/awaytravel.com',
    title: 'Away Travel — Content Creator Collab Program',
    description: 'Partner with Away for travel content. Gifted products + revenue share for qualified content creators in the travel niche.',
    type: 'collab',
    niches: ['Travel', 'Lifestyle'],
    platforms: ['instagram', 'tiktok', 'youtube'],
    commission_rate: 10,
    budget_min: null,
    budget_max: null,
    min_followers: 15000,
    apply_url: 'https://www.awaytravel.com/pages/referral',
    is_featured: true,
  },
  {
    source: 'seed',
    brand_name: 'Lululemon',
    logo_url: 'https://logo.clearbit.com/lululemon.com',
    title: 'lululemon Collective — Ambassador Applications Open',
    description: 'Join the lululemon ambassador community. Product gifting, event invites, and paid content opportunities for fitness creators.',
    type: 'brand_deal',
    niches: ['Fitness', 'Wellness', 'Fashion'],
    platforms: ['instagram', 'tiktok'],
    commission_rate: null,
    budget_min: 500,
    budget_max: 5000,
    min_followers: 10000,
    apply_url: 'https://shop.lululemon.com/story/ambassador',
    is_featured: true,
  },
  {
    source: 'seed',
    brand_name: 'GoPro',
    logo_url: 'https://logo.clearbit.com/gopro.com',
    title: 'GoPro Creator Community — Gear + Paid Collabs',
    description: 'Get gear, early access, and paid collaboration opportunities as a GoPro creator partner. Adventure, travel, and extreme sports focus.',
    type: 'collab',
    niches: ['Travel', 'Sports', 'Adventure', 'Tech'],
    platforms: ['youtube', 'instagram', 'tiktok'],
    commission_rate: 5,
    budget_min: null,
    budget_max: null,
    min_followers: 10000,
    apply_url: 'https://community.gopro.com/s/article/be-a-gopro-creator',
    is_featured: false,
  },
  {
    source: 'seed',
    brand_name: 'Oura Ring',
    logo_url: 'https://logo.clearbit.com/ouraring.com',
    title: 'Oura Ring Ambassador Program — Health Tech Creators',
    description: 'Partner with Oura Ring as a health and wellness creator. Gifted rings, custom discount codes, and performance commission.',
    type: 'brand_deal',
    niches: ['Health', 'Fitness', 'Tech', 'Biohacking'],
    platforms: ['instagram', 'youtube', 'podcast'],
    commission_rate: 10,
    budget_min: null,
    budget_max: null,
    min_followers: 10000,
    apply_url: 'https://ouraring.com/affiliates',
    is_featured: false,
  },
  {
    source: 'seed',
    brand_name: 'Airbnb',
    logo_url: 'https://logo.clearbit.com/airbnb.com',
    title: 'Airbnb Affiliate Program — Travel & Lifestyle Creators',
    description: 'Earn commission for every new host or guest you refer to Airbnb. Ideal for travel and lifestyle creators.',
    type: 'affiliate',
    niches: ['Travel', 'Lifestyle'],
    platforms: ['youtube', 'instagram', 'blog'],
    commission_rate: null,
    budget_min: 5,
    budget_max: 50,
    min_followers: 5000,
    apply_url: 'https://www.airbnb.com/associates',
    is_featured: false,
  },
  {
    source: 'seed',
    brand_name: 'LinkedIn Learning',
    logo_url: 'https://logo.clearbit.com/linkedin.com',
    title: 'LinkedIn Learning Affiliate — 35% commission',
    description: 'Earn 35% on LinkedIn Learning subscriptions. Ideal for B2B, career, and professional development creators.',
    type: 'affiliate',
    niches: ['Education', 'Career', 'B2B'],
    platforms: ['linkedin', 'youtube', 'blog'],
    commission_rate: 35,
    budget_min: null,
    budget_max: null,
    min_followers: 5000,
    apply_url: 'https://learning.linkedin.com/cx/affiliates',
    is_featured: false,
  },
  {
    source: 'seed',
    brand_name: 'ActiveCampaign',
    logo_url: 'https://logo.clearbit.com/activecampaign.com',
    title: 'ActiveCampaign Affiliate — 20–30% recurring',
    description: 'Earn 20–30% recurring commission on all ActiveCampaign subscriptions. Popular email marketing & CRM platform.',
    type: 'affiliate',
    niches: ['Marketing', 'B2B', 'Business'],
    platforms: ['youtube', 'blog'],
    commission_rate: 25,
    budget_min: null,
    budget_max: null,
    min_followers: 1000,
    apply_url: 'https://www.activecampaign.com/partner/affiliate',
    is_featured: false,
  },
]
